name: Rate Limiter Testing Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build and Test
      run: |
        go build ./...
        
    - name: Run 2FA Test
      run: |
        go run build/main.go &
        sleep 5

        chmod +x build/rate_limiter_test.sh
        build/rate_limiter_test.sh

    - name: Stop the server
      run: pkill -f "build/main.go" || true  
